### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by mpranjic** [DrSnowbird/protege-docker-x11#1]
Hi, I am having issues starting the container. Can you help?

```
protegex       | 11:00:52,471 |-INFO in ch.qos.logback.core.FileAppender[files] - File property is set to [/home/developer/.Protege/logs/protege.log]
protegex       | 11:00:52,471 |-ERROR in ch.qos.logback.core.FileAppender[files] - Failed to create parent directories for [/home/developer/.Protege/logs/protege.log]
protegex       | 11:00:52,472 |-ERROR in ch.qos.logback.core.FileAppender[files] - openFile(/home/developer/.Protege/logs/protege.log,true) call failed. java.io.FileNotFoundException: /home/developer/.Protege/logs/protege.log (No such file or directory)
```

This is the configuration I'm using:

```
version: '3'
services:
  protegex:
    image: openkbs/protege-docker-x11
    hostname: protegex
    domainname: mynetwork
    network_mode: mynetwork
    container_name: protegex
    environment:
      - DISPLAY=${DISPLAY:-localhost:0}
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      - USER_NAME=marin # tried without it
    volumes:
      - protegex-logs:/home/developer/.Protege
      - protegex-workspace:/home/developer/workspace-protege
      - protegex-plugins:/home/developer/protege-x11/plugins
volumes:
  protegex-logs:
  protegex-workspace:
  protegex-plugins:
```
